/* * * * * * * * * * * *
 * rudolph.c
 *
 * counts the number of distinct strings created after performing one 
 * instance of several possible replacements
 *
 * also counts how many replacements would have taken place to generate the
 * input string
 * * * * * * * * * * * */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

void parse_input(char input[], char* input_name);
int count_permutations(char input[]);
int case_al(char input[], char record[][500], int n, int record_pos);
int case_b(char input[], char record[][500], int n, int record_pos);
int case_ca(char input[], char record[][500], int n, int record_pos);
int case_f(char input[], char record[][500], int n, int record_pos);
int case_h(char input[], char record[][500], int n, int record_pos);
int case_mg(char input[], char record[][500], int n, int record_pos);
int case_n(char input[], char record[][500], int n, int record_pos);
int case_o(char input[], char record[][500], int n, int record_pos);
int case_p(char input[], char record[][500], int n, int record_pos);
int case_si(char input[], char record[][500], int n, int record_pos);
int case_th(char input[], char record[][500], int n, int record_pos);
int case_ti(char input[], char record[][500], int n, int record_pos);
int count_record(char record[][500]);
int count_steps(char input[]);

int main(int argc, char* argv[])
{
	char input_line[500];

	if (argc != 2)
	{
		printf("Usage: ./rudoph.c <input.txt>\n");
		return 1;
	}

	parse_input(input_line, argv[1]);

	printf("Calibration: %d\n", count_permutations(input_line));

	printf("Fabrication: %d\n", count_steps(input_line));

	return 0;
}

/* reads from input file and parses data into the input[] array 
 */
void parse_input(char input[], char* input_name)
{
	FILE* input_file = fopen(input_name, "r");

	if (!input_file)
	{
		printf("Error: could not open file %s\n", input_name);
		exit(2);
	}

	fgets(input, 500, input_file);
}

/* generates each possible permutation from one replacement in the input[]
 * array
 * returns the result of calling count_record
 */
int count_permutations(char input[])
{
	char record[1000][500];
	int n = 0;
	int record_pos = 0;
	int delta;

	while (input[n] != '\0')
	{
		delta = 0;
		if (islower(input[n + 1]))
		{
			if (input[n] == 'A' && input[n + 1] == 'l')
			{
				delta = case_al(input, record, n, 
						record_pos);
			}
			else if (input[n] == 'C' && input[n + 1] == 'a')
			{
				delta = case_ca(input, record, n, 
						 record_pos);
			}
			else if (input[n] == 'M' && input[n + 1] == 'g')
			{
				delta = case_mg(input, record, n, 
						record_pos);
			}
			else if (input[n] == 'S' && input[n + 1] == 'i')
			{
				delta = case_si(input, record, n,
						record_pos);
			}
			else if (input[n] == 'T' && input[n + 1] == 'h')
			{
				delta = case_th(input, record, n,
						record_pos);
			}
			else if (input[n] == 'T' && input[n + 1] == 'i')
			{
				delta = case_ti(input, record, n,
						record_pos);
			}

			n += 2;
		}
		else
		{
			if (input[n] == 'B')
			{
				delta = case_b(input, record, n, record_pos);
			}
			else if (input[n] == 'F')
			{
				delta = case_f(input, record, n, record_pos);
			}
			else if (input[n] == 'H')
			{
				delta = case_h(input, record, n, record_pos);
			}
			else if (input[n] == 'N')
			{
				delta = case_n(input, record, n, record_pos);
			}
			else if (input[n] == 'O')
			{
				delta = case_o(input, record, n, record_pos);
			}
			else if (input[n] == 'P')
			{
				delta = case_p(input, record, n, record_pos);
			}
			
			n++;
		}

		record_pos += delta;
	}

	return count_record(record);
}

/* all case_ functions record the strings generated by one replacement into
 * the record[][] array
 * returns the number of strings created
 */
int case_al(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with ThF */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'T';
	record[record_pos][n + 1] = 'h';
	record[record_pos][n + 2] = 'F';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos][i] = input[i - 1];
	}

	/* replace with ThRnFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'T';
	record[record_pos + 1][n + 1] = 'h';
	record[record_pos + 1][n + 2] = 'R';
	record[record_pos + 1][n + 3] = 'n';
	record[record_pos + 1][n + 4] = 'F';
	record[record_pos + 1][n + 5] = 'A';
	record[record_pos + 1][n + 6] = 'r';
	for (i = n + 7; i < strlen(input) + 8; i++)
	{
		record[record_pos + 1][i] = input[i - 5];
	}

	return 2;		
}

int case_b(char input[], char record[][500], int n, int record_pos)
{
	int i;
	
	/* replace with BCa */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'B';
	record[record_pos][n + 1] = 'C';
	record[record_pos][n + 2] = 'a';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos][i] = input[i - 2];
	}

	/* replace with TiB */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'T';
	record[record_pos + 1][n + 1] = 'i';
	record[record_pos + 1][n + 2] = 'B';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 1][i] = input[i - 2];
	}

	/* replace with TiRnFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 2][i] = input[i];
	}
	record[record_pos + 2][n] = 'T';
	record[record_pos + 2][n + 1] = 'i';
	record[record_pos + 2][n + 2] = 'R';
	record[record_pos + 2][n + 3] = 'n';
	record[record_pos + 2][n + 4] = 'F';
	record[record_pos + 2][n + 5] = 'A';
	record[record_pos + 2][n + 6] = 'r';
	for (i = n + 7; i < strlen(input) + 8; i++)
	{
		record[record_pos + 2][i] = input[i - 6];
	}

	return 3;
}

int case_ca(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with CaCa */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'a';
	record[record_pos][n + 2] = 'C';
	record[record_pos][n + 3] = 'a';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos][i] = input[i - 2];
	}

	/* replace with PB */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'P';
	record[record_pos + 1][n + 1] = 'B';
	for (i = n + 2; i < strlen(input) + 3; i++)
	{
		record[record_pos + 1][i] = input[i];
	}

	/* replace with PRnFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 2][i] = input[i];
	}
	record[record_pos + 2][n] = 'P';
	record[record_pos + 2][n + 1] = 'R';
	record[record_pos + 2][n + 2] = 'n';
	record[record_pos + 2][n + 3] = 'F';
	record[record_pos + 2][n + 4] = 'A';
	record[record_pos + 2][n + 5] = 'r';
	for (i = n + 6; i < strlen(input) + 7; i++)
	{
		record[record_pos + 2][i] = input[i - 4];
	}

	/* replace with SiRnFYFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 3][i] = input[i];
	}
	record[record_pos + 3][n] = 'S';
	record[record_pos + 3][n + 1] = 'i';
	record[record_pos + 3][n + 2] = 'R';
	record[record_pos + 3][n + 3] = 'n';
	record[record_pos + 3][n + 4] = 'F';
	record[record_pos + 3][n + 5] = 'Y';
	record[record_pos + 3][n + 6] = 'F';
	record[record_pos + 3][n + 7] = 'A';
	record[record_pos + 3][n + 8] = 'r';
	for (i = n + 9; i < strlen(input) + 10; i++)
	{
		record[record_pos + 3][i] = input[i - 7];
	}

	/* replace with SiRnMgAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 4][i] = input[i];
	}
	record[record_pos + 4][n] = 'S';
	record[record_pos + 4][n + 1] = 'i';
	record[record_pos + 4][n + 2] = 'R';
	record[record_pos + 4][n + 3] = 'n';
	record[record_pos + 4][n + 4] = 'M';
	record[record_pos + 4][n + 5] = 'g';
	record[record_pos + 4][n + 6] = 'A';
	record[record_pos + 4][n + 7] = 'r';
	for (i = n + 8; i < strlen(input) + 9; i++)
	{
		record[record_pos + 4][i] = input[i - 6];
	}

	/* replace with SiTh */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 5][i] = input[i];
	}
	record[record_pos + 5][n] = 'S';
	record[record_pos + 5][n + 1] = 'i';
	record[record_pos + 5][n + 2] = 'T';
	record[record_pos + 5][n + 3] = 'h';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos + 5][i] = input[i - 2];
	}

	return 6;
}

int case_f(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with CaF */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'a';
	record[record_pos][n + 2] = 'F';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos][i] = input[i - 2];
	}

	/* replace with PMg */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'P';
	record[record_pos + 1][n + 1] = 'M';
	record[record_pos + 1][n + 2] = 'g';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 1][i] = input[i - 2];
	}

	/* replace with SiAl */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 2][i] = input[i];
	}
	record[record_pos + 2][n] = 'S';
	record[record_pos + 2][n + 1] = 'i';
	record[record_pos + 2][n + 2] = 'A';
	record[record_pos + 2][n + 3] = 'l';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos + 2][i] = input[i - 3];
	}

	return 3;
}

int case_h(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with CRnAlAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'R';
	record[record_pos][n + 2] = 'n';
	record[record_pos][n + 3] = 'A';
	record[record_pos][n + 4] = 'l';
	record[record_pos][n + 5] = 'A';
	record[record_pos][n + 6] = 'r';
	for (i = n + 7; i < strlen(input) + 8; i++)
	{
		record[record_pos][i] = input[i - 6];
	}

	/* replace with CRnFYFYFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'C';
	record[record_pos + 1][n + 1] = 'R';
	record[record_pos + 1][n + 2] = 'n';
	record[record_pos + 1][n + 3] = 'F';
	record[record_pos + 1][n + 4] = 'Y';
	record[record_pos + 1][n + 5] = 'F';
	record[record_pos + 1][n + 6] = 'Y';
	record[record_pos + 1][n + 7] = 'F';
	record[record_pos + 1][n + 8] = 'A';
	record[record_pos + 1][n + 9] = 'r';
	for (i = n + 10; i < strlen(input) + 11; i++)
	{
		record[record_pos + 1][i] = input[i - 9];
	}

	/* replace with CRnFYMgAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 2][i] = input[i];
	}
	record[record_pos + 2][n] = 'C';
	record[record_pos + 2][n + 1] = 'R';
	record[record_pos + 2][n + 2] = 'n';
	record[record_pos + 2][n + 3] = 'F';
	record[record_pos + 2][n + 4] = 'Y';
	record[record_pos + 2][n + 5] = 'M';
	record[record_pos + 2][n + 6] = 'g';
	record[record_pos + 2][n + 7] = 'A';
	record[record_pos + 2][n + 8] = 'r';
	for (i = n + 9; i < strlen(input) + 10; i++)
	{
		record[record_pos + 2][i] = input[i - 8];
	}
	
	/* replace with CRnMgYFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 3][i] = input[i];
	}
	record[record_pos + 3][n] = 'C';
	record[record_pos + 3][n + 1] = 'R';
	record[record_pos + 3][n + 2] = 'n';
	record[record_pos + 3][n + 3] = 'M';
	record[record_pos + 3][n + 4] = 'g';
	record[record_pos + 3][n + 5] = 'Y';
	record[record_pos + 3][n + 6] = 'F';
	record[record_pos + 3][n + 7] = 'A';
	record[record_pos + 3][n + 8] = 'r';
	for (i = n + 9; i < strlen(input) + 10; i++)
	{
		record[record_pos + 3][i] = input[i - 8];
	}

	/* replace with HCa */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 4][i] = input[i];
	}
	record[record_pos + 4][n] = 'H';
	record[record_pos + 4][n + 1] = 'C';
	record[record_pos + 4][n + 2] = 'a';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 4][i] = input[i - 2];
	}

	/* replace with NRnFYFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 5][i] = input[i];
	}
	record[record_pos + 5][n] = 'N';
	record[record_pos + 5][n + 1] = 'R';
	record[record_pos + 5][n + 2] = 'n';
	record[record_pos + 5][n + 3] = 'F';
	record[record_pos + 5][n + 4] = 'Y';
	record[record_pos + 5][n + 5] = 'F';
	record[record_pos + 5][n + 6] = 'A';
	record[record_pos + 5][n + 7] = 'r';
	for (i = n + 8; i < strlen(input) + 9; i++)
	{
		record[record_pos + 5][i] = input[i - 7];
	}

	/* replace with NRnMgAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 6][i] = input[i];
	}
	record[record_pos + 6][n] = 'N';
	record[record_pos + 6][n + 1] = 'R';
	record[record_pos + 6][n + 2] = 'n';
	record[record_pos + 6][n + 3] = 'M';
	record[record_pos + 6][n + 4] = 'g';
	record[record_pos + 6][n + 5] = 'A';
	record[record_pos + 6][n + 6] = 'r';
	for (i = n + 7; i < strlen(input) + 8; i++)
	{
		record[record_pos + 6][i] = input[i - 6];
	}

	/* replace with NTh */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 7][i] = input[i];
	}
	record[record_pos + 7][n] = 'N';
	record[record_pos + 7][n + 1] = 'T';
	record[record_pos + 7][n + 2] = 'h';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 7][i] = input[i - 2];
	}
	
	/* replace with OB */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 8][i] = input[i];
	}
	record[record_pos + 8][n] = 'O';
	record[record_pos + 8][n + 1] = 'B';
	for (i = n + 2; i < strlen(input) + 3; i++)
	{
		record[record_pos + 8][i] = input[i - 1];
	}

	/* replace with ORnFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 9][i] = input[i];
	}
	record[record_pos + 9][n] = 'O';
	record[record_pos + 9][n + 1] = 'R';
	record[record_pos + 9][n + 2] = 'n';
	record[record_pos + 9][n + 3] = 'F';
	record[record_pos + 9][n + 4] = 'A';
	record[record_pos + 9][n + 5] = 'r';
	for (i = n + 6; i < strlen(input) + 7; i++)
	{
		record[record_pos + 9][i] = input[i - 5];
	}

	return 10;
}

int case_mg(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with BF */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'B';
	record[record_pos][n + 1] = 'F';
	for (i = n + 2; i < strlen(input) + 3; i++)
	{
		record[record_pos][i] = input[i];
	}

	/* replace with TiMg */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'T';
	record[record_pos + 1][n + 1] = 'i';
	record[record_pos + 1][n + 2] = 'M';
	record[record_pos + 1][n + 3] = 'g';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos + 1][i] = input[i - 2];
	}

	return 2;
}

int case_n(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with CRnFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'R';
	record[record_pos][n + 2] = 'n';
	record[record_pos][n + 3] = 'F';
	record[record_pos][n + 4] = 'A';
	record[record_pos][n + 5] = 'r';
	for (i = n + 6; i < strlen(input) + 7; i++)
	{
		record[record_pos][i] = input[i - 5];
	}

	/* replace with HSi */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'H';
	record[record_pos + 1][n + 1] = 'S';
	record[record_pos + 1][n + 2] = 'i';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 1][i] = input[i - 2];
	}

	return 2;
}

int case_o(char input[], char record[][500], int n, int record_pos)
{
	int i;
	printf("o\t%d\n", n);
	
	/* replace with CRnFYFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'R';
	record[record_pos][n + 2] = 'n';
	record[record_pos][n + 3] = 'F';
	record[record_pos][n + 4] = 'Y';
	record[record_pos][n + 5] = 'F';
	record[record_pos][n + 6] = 'A';
	record[record_pos][n + 7] = 'r';
	for (i = n + 8; i < strlen(input) + 9; i++)
	{
		record[record_pos][i] = input[i - 7];
	}
	
	/* replace with CRnMgAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'C';
	record[record_pos + 1][n + 1] = 'R';
	record[record_pos + 1][n + 2] = 'n';
	record[record_pos + 1][n + 3] = 'M';
	record[record_pos + 1][n + 4] = 'g';
	record[record_pos + 1][n + 5] = 'A';
	record[record_pos + 1][n + 6] = 'r';
	for (i = n + 7; i < strlen(input) + 8; i++)
	{
		record[record_pos + 1][i] = input[i - 6];
	}

	/* replace with HP */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 2][i] = input[i];
	}
	record[record_pos + 2][n] = 'H';
	record[record_pos + 2][n + 1] = 'P';
	for (i = n + 2; i < strlen(input) + 3; i++)
	{
		record[record_pos + 2][i] = input[i - 1];
	}
	
	/* replace with NRnFAr */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 3][i] = input[i];
	}
	record[record_pos + 3][n] = 'N';
	record[record_pos + 3][n + 1] = 'R';
	record[record_pos + 3][n + 2] = 'n';
	record[record_pos + 3][n + 3] = 'F';
	record[record_pos + 3][n + 4] = 'A';
	record[record_pos + 3][n + 5] = 'r';
	for (i = n + 6; i < strlen(input) + 7; i++)
	{
		record[record_pos + 3][i] = input[i - 5];
	}

	/* replace with OTi */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 4][i] = input[i];
	}
	record[record_pos + 4][n] = 'O';
	record[record_pos + 4][n + 1] = 'T';
	record[record_pos + 4][n + 2] = 'i';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 4][i] = input[i - 2];
	}

	return 5;
}

int case_p(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with CaP */
       	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'a';
	record[record_pos][n + 2] = 'P';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos][i] = input[i - 2];
	}

	/* replace with PTi */
      	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'P';
	record[record_pos + 1][n + 1] = 'T';
	record[record_pos + 1][n + 2] = 'i';
	for (i = n + 3; i < strlen(input) + 4; i++)
	{
		record[record_pos + 1][i] = input[i - 2];
	}

	/* replace with SiRnFAr */
      	for (i = 0; i < n; i++)
	{
		record[record_pos + 2][i] = input[i];
	}
	record[record_pos + 2][n] = 'S';
	record[record_pos + 2][n + 1] = 'i';
	record[record_pos + 2][n + 2] = 'R';
	record[record_pos + 2][n + 3] = 'n';
	record[record_pos + 2][n + 4] = 'F';
	record[record_pos + 2][n + 5] = 'A';
	record[record_pos + 2][n + 6] = 'r';
	for (i = n + 7; i < strlen(input) + 8; i++)
	{
		record[record_pos + 2][i] = input[i - 6];
	}

	return 3;
}

int case_si(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with CaSi */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'C';
	record[record_pos][n + 1] = 'a';
	record[record_pos][n + 2] = 'S';
	record[record_pos][n + 3] = 'i';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos][i] = input[i - 2];
	}

	return 1;
}

int case_th(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with ThCa */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'T';
	record[record_pos][n + 1] = 'h';
	record[record_pos][n + 2] = 'C';
	record[record_pos][n + 3] = 'a';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos][i] = input[i - 2];
	}

	return 1;
}

int case_ti(char input[], char record[][500], int n, int record_pos)
{
	int i;

	/* replace with BP */
	for (i = 0; i < n; i++)
	{
		record[record_pos][i] = input[i];
	}
	record[record_pos][n] = 'B';
	record[record_pos][n + 1] = 'P';
	for (i = n + 2; i < strlen(input) + 3; i++)
	{
		record[record_pos][i] = input[i];
	}
	/* replace with TiTi */
	for (i = 0; i < n; i++)
	{
		record[record_pos + 1][i] = input[i];
	}
	record[record_pos + 1][n] = 'T';
	record[record_pos + 1][n + 1] = 'i';
	record[record_pos + 1][n + 2] = 'T';
	record[record_pos + 1][n + 3] = 'i';
	for (i = n + 4; i < strlen(input) + 5; i++)
	{
		record[record_pos + 1][i] = input[i - 2];
	}

	return 2;
}

/* returns the number of unique non-null strings in the record[][] array
 */
int count_record(char record[][500])
{
	int i, j;
	int record_bool[1000] = { 0 };
	int count = 0;

	for (i = 0; i < 1000; i++)
	{
		if (record[i][0] == '\0')
		{
			record_bool[i] = 1;
		}
		if (record_bool[i] == 0)
		{
			for (j = i + 1; j < 1000; j++)
			{
				if (!strcmp(record[i], record[j]))
				{
					record_bool[j] = 1;
				}
			}
		}
	}
	
	for (i = 0; i < 1000; i++)
	{
		if (record[i][0] == '\0')
		{
			break;
		}
		if (record_bool[i] == 0)
		{
			count++;
		}
	}

	return count;
}

/* counts the number of steps necessary to generate the input string
 */
int count_steps(char input[])
{
	int i = 0;
	int count = 0;
	printf("\n%s \n", input);
	
	while (input[i] != '\0')
	{
		if (input[i] == 'R' && input[i + 1] == 'n')
		{
			i += 2;
		}
		else if (input[i] == 'A' && input[i + 1] == 'r')
		{
			i += 2;
		}
		else if (input[i] == 'Y')
		{
			count--;
			i++;
		}
		else if (islower(input[i + 1]))
		{
			count++;
			i += 2;
		}
		else if (isupper(input[i]))
		{
			count++;
			i++;
		}
		else
		{
			i++;
		}
	}

	return count - 1;
}

